index.js
package.json
readme.md

Demo: https://onerous-pencil.surge.sh/flamegraph.html
---
- Fixes zooming out to all stacks in Firefox
- Performance improvements
- only apply constant CSS values on .enter() (could move this to CSS classes possibly for more wins)
- remove hidden elements from the selection to reduce the amount of DOM nodes that need to be animated
---
Fixed a fair few things so it renders now, remaining issues:
I think to fix it we have to find the lowest non-hidden frame and use its width in the `frameWidth()` calculation?

Update to v5

---

index.js
package.json
readme.md

Preview: http://adamant-sponge.surge.sh/flamegraph.html
This builds on https://github.com/davidmarkclements/d3-fg/pull/2 by replacing the SVG rendering bits with Canvas.
It's a lot easier to draw 1000s of shapes on a Canvas compared to the DOM.
The animations are now implemented by using `requestAnimationFrame` and the d3 easing functions directly, instead of using D3 transitions.
The `setGraphZoom` method now uses d3-zoom rather than a CSS `transform:scale()` call, which ensures that everything is redrawn at the correct resolution. d3-zoom also includes panning so that works as well: when zoomed in, you can drag around.
The tooltip is implemented manually because everything has to be done manually with Canvas, it works OK but feels a bit rough sometimes to me, a future improvement could …

Render to canvas

---

index.js

This way the canvas width is the same as the width of its contents.
It fixes an issue where making the screen larger would cut off the graph
at the old, smaller, size:

Resize canvas and rerender after .width() or .height() call

---

index.js

Adds node zooming methods.
- Do `graph.zoom(dataNode)` to zoom in on a node programmatically.
- Do `graph.on('zoom', (dataNode) => {})` to listen for node zoom changes.
This allows 0x to implement history management, like updating the
URL hash when a user zooms in on an entry and telling the graph to
zoom in on a different node when the user goes back in the browser
history.
Previously it was not possible to pick a different node while a zoom
animation was ongoing. It was not a problem because users could just
wait the few 100ms to click the next node. However, with the
programmatically controlled `graph.zoom()` function, it's feasible to
flick through nodes very quickly; eg when connected to the browser back
button. Without this patch you could end up with an outdated state
because zoom …

Node zoom API

---

index.js

Previously the "all stacks" width calculation would fail if no data was recorded, because the "all stacks" frame did not have children. With this patch, it just shows an empty graph:
This `if children ? sum : 0` check is used for all other width calculations already, I just didn't realise that the topmost frame could have no children.

Fix crash when no data was recorded

---

index.js

Previously zooming the entire graph would cause tooltips to show up in
the wrong place. Now, the zoomTransform is applied to the tooltip
position as well.
This patch also scales the font size inside tooltips. When zooming in,
the font size grows similarly to the font inside the stack frames. There
are some arbitrary upper and lower bounds on the font size, trying to
keep it large enough to be readable on low zoom levels, and small enough
to fit on a screen on high zoom levels.

Fix tooltip position when zoomed using +/- buttons

---

index.js

tiny tweak that reads a bit better
```
Top of Stack:0.1%
```
→
```
Top of Stack: 0.1%
```

Add space between "on stack:" and percentage

---

index.js
readme.md

Currently the colour scheme used by d3-fg is hardcoded in. This allows a colour setting function to be passed in to D3-FG as an option, so that other palettes can be used.

Allow colorHash function to be overridden

---

index.js
readme.md

This adds a `heatBars` option that, when set to `true`, causes d3-fg to draw the heat colour in a bar on _top_ of each stack frame. When `false`, it still draws the heat colour as the background colour of the stack frame.
Additionally, this patch adds the following styling options:
- `frameColors` - a `{fill, stroke}` object. If heatBars mode is enabled, this will determine the fill and stroke style for all stack frames. If heatBars mode is disabled, it will only be used for the "all stacks" pseudo-frame at the bottom.
- `labelColors` - an object containing label text colors. The keys are type names like "app", "deps", "core", and values are the colors that should be used for labels on the stack frames of that type. `labelColors.default` is used if a color is not configured for a given …

Add `heatBars` mode, add color options

---

index.js

Previously when updating the canvas (as result of the resize event) the following condition was preventing the canvas to be actually updated with the new size:
`if (devicePixelRatio !== window.devicePixelRatio) {`
This resulted in the canvas cutting off part of the chart on the far right side:
I am now moving this condition to control the `canvas.scale` method only.

resizing the canvas element whenever the `update` function gets executed

---

index.js

`clearRect()` is affected by scaling and such done outside it, but we
need the `canvas.width` and `canvas.height` to actually line up with the
canvas borders here. Using `setTransform()` we can remove all current
scaling transforms.

Fix clearing canvas on all DPI / zoom / panning levels

---

index.js

With this PR d3-fg will expose the `getNodeRect` public method.
It accepts the node `data` object and it returns an object containing the node position and size (or `null` if no node is found).
The returned object has now the following shape:
`{x, y, width, height}`
This has been updated to match the object shape returned by `getClientBoundingRect`.
This method is useful when we need to overlap external components over a particular frame, like the following screenshot demonstrates:

Exposing `getNodeRect`

---

index.js
readme.md

1. Makes writing the on-Canvas labels able to be disabled or overridden
2. Makes the default click action (zooming in or out) able to be disabled or overridden
- Any function passed in `clickHandler` acts like a typical d3 event handler in that if it is not defined inside an arrow function, `this` inside the function is the relevant DOM element (the canvas)
3. Also allows `clickin` and `clickout` events to be listened to, same as `hoverin` and `hoverout`
- So, applications can handle click events before the default d3-fg click handler, if they want to keep the default click behaviour
4. Updates the readme, with docs for all overridable functions and listenable dispatches.

Allow renderLabel and click handler to be overridden, add click dispatch event

---

index.js
readme.md

This is a bit tough to explain so I've got words here and images down below :point_down: 
In 0x, hidden stack frames still take up space. That's visible as empty
space between different stacks: one of the stacks is a child of a hidden
stack frame. This is the easiest thing to do d3 wise and has the nice
benefit that stack frames only move vertically when you toggle frame
visibility.
This PR adds a `collapseHiddenNodeWidths: true` option to change that
behaviour. Hidden stack frames don't take up horizontal space when this
option is set. That means that child stacks of hidden stack frames are
bunched up next to each other without empty space in between. The
benefit of this approach is that, combined with `heatBars: true`, the
heat bars will be one contiguous block, and the size of this …

Add option for hidden stack frame alignment

---

index.js
readme.md

Allows the function that renders individual stack frame boxes to be overridden so applications using d3-fg can style their boxes however they want. This includes setting fills, strokes, drawing any additional lines and applying and removing any custom styles to hovered nodes.
It requires exposing quite a lot of d3-fg global variables, so these have been hoovered up and passes as an object alongside the object containing the node-specific arguments.

Allow renderStackFrameBox to be overridden

---

index.js

This PR fixes the `chart.cellHeight` method.
It now updates the canvas height and re-renders the graph whenever the cell height gets updated

updating the canvas height and re-rendering when changing the cellHeight

---

index.js
readme.md

Allows the default filter logic to be overridden. Currently, d3-fg excludes based on whether the node data has a property, `type`, that is in the filterTypes array (generated from the `exclude` iterable).
This allows that check to be overridden so that third parties can implement their own filter logic, checking against other (or multiple) properties.
As with other such overridable functions, the default function is used if no option is passed in, and the feature is disabled if null is passed instead of a function (which in this case shows everything).

Add overridable filter function, isNodeExcluded

---

index.js

This simply uses the ternary used to set `h` initially when recalculating the chart height to help resolve [this Clinic Flame issue](https://github.com/nearform/node-clinic-flame/issues/52)

Ensure minHeight is used when calculating the chart height

---

index.js

(patch)
Currently, d3-fg contains many d3 selectors that match any `canvas` element in the supplied HTML wrapper, assuming that the main flamegraph will be the only such canvas element. This adds `.d3-flame-graph` (the more specific of the two classes d3-fg applies) to the selector, so there aren't conflicts if a third party adds a canvas sibling (e.g. https://github.com/nearform/node-clinic-flame/pull/79).
Checked on Clinic Flame and 0x.

Make canvas selectors more specific

---

package.json

There is `require('d3-dispatch')` in index.js but d3-dispatch is not in package.json, it only works because it's an implicit dep of packages that are.

Make implicit dep "d3-dispatch" explicit

---

index.js

For https://github.com/davidmarkclements/0x/pull/218
Gives wasm a minty colour, and excludes the [WASM] bit at the end from the search filter. It's not using the same `.split('[')[0]` way as the cpp filter because I'm sure there's some language out there that will put [] in the middle of a function name

Add wasm color and search filter
